version: '3'

services:
  web:
    build:
      context: .
      dockerfile: DockerfileLemeleVizier.web
    ports:
      - "1234:80"
    depends_on:
      - db
    environment:
      DB_SERVER: ${DVWA_DB_SERVER}
      DB_USERNAME: ${DVWA_DB_USERNAME}
      DB_PASSWORD: ${DVWA_DB_PASSWORD}
      DB_DATABASE: ${DVWA_DB_DATABASE}
      
  db:
    build:
      context: .
      dockerfile: DockerfileLemeleVizier.bdd
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
