version: '3'

services:
  web:
    build:
      context: .
      dockerfile: DockerfileLemeleVizier.web
    ports:
      - "1234:80"
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_USERNAME: dvwa
      DB_PASSWORD: p@ssw0rd
      DB_DATABASE: dvwa
  db:
    build:
      context: .
      dockerfile: DockerfileLemeleVizier.bdd
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
